services:
  ml_service_mongo:
    image: mongo:4.4.6
    container_name: ml-service-mongodb
    restart: always
    volumes:
      - mongo_data_recruitease:/data/db
      - ./init-mongo.sh:/docker-entrypoint-initdb.d/init-mongo.sh:ro
    ports:
      - "${MONGO_PORT}:27017"
    environment: 
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_USERNAME: ${MONGO_USERNAME}
      MONGO_PASSWORD: ${MONGO_PASSWORD}
      MONGO_HOST: ${MONGO_HOST}
      MONGO_PORT: ${MONGO_PORT}
      MONGO_DB: ${MONGO_DB}
    networks:
      - internal
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo localhost:27017/?authSource=admin --quiet
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

  ml_service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: recruitease-ml-service
    depends_on:
      ml_service_mongo:
        condition: service_healthy
    networks:
      - internal
    env_file:
      - .env

networks:
  internal:
    external: true
    name: recruitease-network

volumes:
  mongo_data_recruitease:  